name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: '**/node_modules'
        key: ${{ runner.os }}-modules--${{ hashFiles('**/yarn.lock') }}--${{ hashFiles('**/package.json') }}

    - run:  npm config set scripts-prepend-node-path true

    - run: npm install -g yarn

    - run: yarn install

    - run: yarn build
      env:
        NODE_ENV: production

    - run: yarn test
      env:
        NODE_ENV: test
